#!/usr/bin/env bash
# script that performs a 301 redirection

sudo apt-get update
sudo apt-get install -y nginx
sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

string_to_redirect="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/254guru permanent;"

sudo sed -i "s/server_name _;/$string_to_redirect/" /etc/nginx/sites-enabled/default

sudo service nginx restart
