#!/usr/bin/env bash
# a Bash script that displays "To infinity and beyond" indefinitely, with a 2-second pause between each iteration of the loop:
while true; do
    echo "To infinity and beyond"
    sleep 2
done

