#!/usr/bin/env bash
# Find the PID of the process named "7-highlander"
process_name="7-highlander"
pid=$(pgrep -f "$process_name")

if [ -n "$pid" ]; then
    echo "Stopping process $pid: $process_name"
    kill "$pid"
    echo "Process stopped."
else
    echo "No process with the name '$process_name' is running."
fi

