#!/usr/bin/env bash
# Use a for loop to iterate from 1 to 100
for ((i=1; i<=100; i++))
do
    # Check for multiples of 3 and 5 (FizzBuzz)
    if ((i % 3 == 0)) && ((i % 5 == 0)); then
        echo "FizzBuzz"
    # Check for multiples of 3 (Fizz)
    elif ((i % 3 == 0)); then
        echo "Fizz"
    # Check for multiples of 5 (Buzz)
    elif ((i % 5 == 0)); then
        echo "Buzz"
    # Otherwise, display the number
    else
        echo "$i"
    fi
done

