#!/usr/bin/env bash
# Run Nginx as Nginx privilaged user

sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

sed -i "s/80/8080/g" /etc/nginx/sites-available/default
#change permission
chmod 644 /etc/nginx/nginx.conf

#kill apache2 service
pkill apache2

sudo -u nginx service nginx restart

